import { chromium } from 'playwright';
const URL='https://combat-coach-landing.vercel.app/';
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true})).newPage();
const errs=[];
p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/i.test(m.text()))errs.push(m.text());});
await p.goto(URL,{waitUntil:'load'});
await p.waitForTimeout(1500);
const vh=await p.evaluate(()=>innerHeight), docH=await p.evaluate(()=>document.documentElement.scrollHeight);
await p.evaluate(()=>document.getElementById('train').scrollIntoView()); await p.waitForTimeout(700);
const trainOk=await p.evaluate(()=>!!document.querySelector('.trainx-mobile .tcard.active'));
await p.evaluate(()=>document.getElementById('app').scrollIntoView()); await p.waitForTimeout(700);
const appCards=await p.evaluate(()=>document.querySelectorAll('.appx-mobile .acard').length);
const appActive=await p.evaluate(()=>!!document.querySelector('.appx-mobile .acard.active'));
await b.close();
console.log('LIVE PROD check @ '+URL);
console.log('  screens:', (docH/vh).toFixed(1));
console.log('  train carousel active:', trainOk?'YES':'NO');
console.log('  app carousel:', appCards+' cards, active='+(appActive?'YES':'NO'));
console.log('  JS errors:', errs.length?('FAIL '+errs.slice(0,3)):'none');
